<?php
// $Id$

/**
 * @file
 * Adds a custom Plugs Settings page and other nifty stuff.
 *
 * This module is for Drupal 6.x only.
 *
 * Module by: Sprocket, http://www.sprocketcreative.com
 */

/**
 * Implementation of hook_menu().
 *
function plugs_menu() {

}
// */

/**
 * Implementation of hook_perm().
 */
function plugs_perm() {
  return array('administer plugs');
}

/**
 * Implementation of hook_nodeapi().
 */
function plugs_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if($node->type == 'plug') {
    $path = drupal_get_path('module', 'plugs');
    switch($op) {
      case 'validate':
      case 'prepare':
        drupal_add_js($path .'/plugs.js');
        break;
        
      case 'view':
        //drupal_add_css($path .'/plugs.css');
        //$node->content['body']['#value'] = theme('plug', $node);
        break;
    }
  }
}

/**
 * Implementation of hook_view_api().
 */
function plugs_views_api() {
  return array(
    'api' => 2.0,
  );
}

/**
 * Implementation of hook_imagecache_default_presets().
 */
function plugs_imagecache_default_presets() {
  $presets = array();

  $presets['plug'] = array (
    'presetname' => 'plug',
    'actions' => 
    array (
      array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale_and_crop',
        'data' => 
        array (
          'width' => '269',
          'height' => '97',
        ),
      ),
    ),
  );

  return $presets;
}